Create ega_dataset
BioSchemas/specifications pull request #252
Opened 2018-11-23 13:05 UTC by ivyEBI

How the EGA data mapped to bioschema

2018-11-23 13:13 UTC, jdylan reviewed
This is an EGA study not dataset

2018-11-23 13:51 UTC, ivyEBI reviewed
update a new example

2018-12-03 15:16 UTC, AlasdairGray requested changes
As @jdylan has said, this markup seems to be describing a Study rather than a Dataset. On the corresponding webpage I see that the Study makes a single Dataset available. Should this page be marked up using the [Study profile](http://bioschemas.org/devSpecs/Study/) (in development) and the [page about the Dataset](https://ega-archive.org/datasets/EGAD00001002262) marked up with the Dataset profile?

2018-12-03 15:16 UTC, AlasdairGray commented on Dataset/examples/ega_study
> +    "keywords": "null",
Nulls should not be used

2018-12-03 15:16 UTC, AlasdairGray commented on Dataset/examples/ega_study
> +        "others"
This is not very informative

2018-12-03 15:16 UTC, AlasdairGray commented on Dataset/examples/ega_study
> +    "license": "null",
Null should not be used

2018-12-14 10:37 UTC, AlasdairGray commented
@ivyEBI @jdylan  let me know if you need help making the requested changes.

2019-07-23 15:53 UTC, AlasdairGray commented
As there has been no action to correct this pull request, we are going to close it.

2019-07-23 15:53 UTC, closed without merging